### ISSUE TITLE
[BUG] Config screen doesn't render

### ISSUE THREAD

**Issue by Noobly-Walker** [Povstalec/StellarView#10]
Minecraft Version: 1.20.2
Forge Version: 48.1.0
Mod Version: 0.2.2
Other mods present (if it matters): 
- DistantHorizons v2.0.1a
- InventoryProfilesNext v1.10.10
- KotlinForForge v4.10.0
- libIPN v4.0.2
- Optifine v1.20.2 U_I7_pre1
- XaerosMinimap v24.1.1
- XaerosWorldmap v1.38.4

Put simply, I pressed [G], which is the key bound to open up StellarView's debug screen, and the result was that the minimap disappeared, and my cursor was unbound from the camera, but a menu GUI did not appear.

**Comment by Povstalec** [comment]
Interesting, I wonder what might have caused that

**Comment by Noobly-Walker** [comment]
Interestingly, if I run without any other mods, the game just crashes outright on pressing [G].

---- Minecraft Crash Report ----
// You're mean.
Time: 2024-04-27 16:16:38
Description: Rendering screen

java.lang.NoSuchMethodError: 'void net.povstalec.stellarview.client.screens.config.ConfigScreen.m_280273_(net.minecraft.client.gui.GuiGraphics)'
at net.povstalec.stellarview.client.screens.config.ConfigScreen.m_88315_(ConfigScreen.java:47) ~[Stellar%20View-1.20.1-0.2.2.jar%23151!/:0.2.2] {re:classloading}
at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.2-20230921.100330-srg.jar%23152!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:395) ~[forge-1.20.2-48.1.0-universal.jar%23157!/:?] {re:classloading}
at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:389) ~[forge-1.20.2-48.1.0-universal.jar%23157!/:?] {re:classloading}
at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:966) ~[client-1.20.2-20230921.100330-srg.jar%23152!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1211) ~[client-1.20.2-20230921.100330-srg.jar%23152!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:781) ~[client-1.20.2-20230921.100330-srg.jar%23152!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.client.main.Main.main(Main.java:221) ~[1.20.2-forge-48.1.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:98) ~[fmlloader-1.20.2-48.1.0.jar:?] {}
at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:82) ~[fmlloader-1.20.2-48.1.0.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:17) ~[modlauncher-10.1.1.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:40) ~[modlauncher-10.1.1.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:58) ~[modlauncher-10.1.1.jar:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:96) ~[modlauncher-10.1.1.jar:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-10.1.1.jar:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:13) ~[modlauncher-10.1.1.jar:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:10) ~[modlauncher-10.1.1.jar:?] {}
at net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:126) ~[bootstrap-1.2.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod:
Stellar View (stellarview), Version: 0.2.2
Issue tracker URL: https://github.com/Povstalec/StellarView/issues
at TRANSFORMER/stellarview@0.2.2/net.povstalec.stellarview.client.screens.config.ConfigScreen.m_88315_(ConfigScreen.java:47)
Stacktrace:
at net.povstalec.stellarview.client.screens.config.ConfigScreen.m_88315_(ConfigScreen.java:47) ~[Stellar%20View-1.20.1-0.2.2.jar%23151!/:0.2.2] {re:classloading}
at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.2-20230921.100330-srg.jar%23152!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:395) ~[forge-1.20.2-48.1.0-universal.jar%23157!/:?] {re:classloading}
at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:389) ~[forge-1.20.2-48.1.0-universal.jar%23157!/:?] {re:classloading}
-- Screen render details --
Details:
Screen name: net.povstalec.stellarview.client.screens.config.ConfigScreen
Mouse location: Scaled: (480, 254). Absolute: (960.000000, 508.000000)
Screen size: Scaled: (960, 509). Absolute: (1920, 1017). Scale factor of 2.000000
Stacktrace:
at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:966) ~[client-1.20.2-20230921.100330-srg.jar%23152!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1211) ~[client-1.20.2-20230921.100330-srg.jar%23152!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:781) ~[client-1.20.2-20230921.100330-srg.jar%23152!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.client.main.Main.main(Main.java:221) ~[1.20.2-forge-48.1.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:98) ~[fmlloader-1.20.2-48.1.0.jar:?] {}
at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:82) ~[fmlloader-1.20.2-48.1.0.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:17) ~[modlauncher-10.1.1.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:40) ~[modlauncher-10.1.1.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:58) ~[modlauncher-10.1.1.jar:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:96) ~[modlauncher-10.1.1.jar:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-10.1.1.jar:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:13) ~[modlauncher-10.1.1.jar:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:10) ~[modlauncher-10.1.1.jar:?] {}
at net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:126) ~[bootstrap-1.2.0.jar:?] {}

-- Affected level --
Details:
All players: 1 total; [LocalPlayer['Noobly20932'/5099, l='ClientLevel', x=11.11, y=80.00, z=8.63]]
Chunk stats: 1089, 326
Level dimension: minecraft:overworld
Level spawn location: World: (232,36,-456), Section: (at 8,4,8 in 14,2,-29; chunk contains blocks 224,-64,-464 to 239,319,-449), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
Level time: 452203784 game time, 348644404 day time
Server brand: Waterfall (git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560)
Server type: Non-integrated multiplayer server
Stacktrace:
at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:448) ~[client-1.20.2-20230921.100330-srg.jar%23152!/:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2395) ~[client-1.20.2-20230921.100330-srg.jar%23152!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:798) ~[client-1.20.2-20230921.100330-srg.jar%23152!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.client.main.Main.main(Main.java:221) ~[1.20.2-forge-48.1.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:98) ~[fmlloader-1.20.2-48.1.0.jar:?] {}
at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:82) ~[fmlloader-1.20.2-48.1.0.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:17) ~[modlauncher-10.1.1.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:40) ~[modlauncher-10.1.1.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:58) ~[modlauncher-10.1.1.jar:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:96) ~[modlauncher-10.1.1.jar:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-10.1.1.jar:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:13) ~[modlauncher-10.1.1.jar:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:10) ~[modlauncher-10.1.1.jar:?] {}
at net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:126) ~[bootstrap-1.2.0.jar:?] {}

-- Last reload --
Details:
Reload number: 1
Reload reason: initial
Finished: Yes
Packs: mod_resources, vanilla, file/BuildFarm, file/SilverwindFox, file/SRSMPmusic.zip
-- System Details --
Details:
Minecraft Version: 1.20.2
Minecraft Version ID: 1.20.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 17.0.8, Microsoft
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
Memory: 406055328 bytes (387 MiB) / 1040187392 bytes (992 MiB) up to 5368709120 bytes (5120 MiB)
CPUs: 12
Processor Vendor: AuthenticAMD
Processor Name: AMD Ryzen 5 3600 6-Core Processor
Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
Microarchitecture: Zen 2
Frequency (GHz): 3.59
Number of physical packages: 1
Number of physical CPUs: 6
Number of logical CPUs: 12
Graphics card #0 name: NVIDIA GeForce GTX 1660
Graphics card #0 vendor: NVIDIA (0x10de)
Graphics card #0 VRAM (MB): 4095.00
Graphics card #0 deviceId: 0x2184
Graphics card #0 versionInfo: DriverVersion=31.0.15.5186
Memory slot #0 capacity (MB): 8192.00
Memory slot #0 clockSpeed (GHz): 3.20
Memory slot #0 type: DDR4
Memory slot #1 capacity (MB): 8192.00
Memory slot #1 clockSpeed (GHz): 3.20
Memory slot #1 type: DDR4
Memory slot #2 capacity (MB): 8192.00
Memory slot #2 clockSpeed (GHz): 3.20
Memory slot #2 type: DDR4
Memory slot #3 capacity (MB): 8192.00
Memory slot #3 clockSpeed (GHz): 3.20
Memory slot #3 type: DDR4
Virtual memory max (MB): 51129.84
Virtual memory used (MB): 43206.45
Swap memory total (MB): 18432.00
Swap memory used (MB): 2604.00
JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
JVM uptime in seconds: 24.659
Launched Version: 1.20.2-forge-48.1.0
Backend library: LWJGL version 3.3.2+13
Backend API: NVIDIA GeForce GTX 1660/PCIe/SSE2 GL version 4.6.0 NVIDIA 551.86, NVIDIA Corporation
Window size: 1920x1017
GL Caps: Using framebuffer using OpenGL 3.2
GL debug messages:
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'forge'
Type: Client (map_client.txt)
Graphics mode: fancy
Resource Packs: vanilla, file/BuildFarm (incompatible), file/SilverwindFox (incompatible), file/SRSMPmusic.zip (incompatible)
Current Language: en_us
Locale: en_US
CPU: 12x AMD Ryzen 5 3600 6-Core Processor
ModLauncher: 10.1.1
ModLauncher launch target: forge_client
ModLauncher naming: srg
ModLauncher services:
mixin-0.8.5.jar mixin PLUGINSERVICE
eventbus-6.2.0.jar eventbus PLUGINSERVICE
fmlloader-1.20.2-48.1.0.jar slf4jfixer PLUGINSERVICE
fmlloader-1.20.2-48.1.0.jar object_holder_definalize PLUGINSERVICE
fmlloader-1.20.2-48.1.0.jar runtime_enum_extender PLUGINSERVICE
fmlloader-1.20.2-48.1.0.jar capability_token_subclass PLUGINSERVICE
accesstransformers-8.1.1.jar accesstransformer PLUGINSERVICE
fmlloader-1.20.2-48.1.0.jar runtimedistcleaner PLUGINSERVICE
modlauncher-10.1.1.jar mixin TRANSFORMATIONSERVICE
modlauncher-10.1.1.jar fml TRANSFORMATIONSERVICE
FML Language Providers:
minecraft@1.0
lowcodefml@48
javafml@null
Mod List:
client-1.20.2-20230921.100330-srg.jar             |Minecraft                     |minecraft                     |1.20.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
forge-1.20.2-48.1.0-universal.jar                 |Forge                         |forge                         |48.1.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
Stellar View-1.20.1-0.2.2.jar                     |Stellar View                  |stellarview                   |0.2.2               |DONE      |Manifest: NOSIGNATURE
Crash Report UUID: fce8498c-5818-47f1-a552-99a278b972d6
FML: 48.1
Forge: net.minecraftforge:48.1.0
[16:16:39] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 01add68c-4b02-4153-899b-79fa40291243
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Noobly\AppData\Roaming\.minecraft\crash-reports\crash-2024-04-27_16.16.38-client.txt
Process Monitor
Process crashed with exit code -1073740791

**Comment by Noobly-Walker** [comment]
There is a non-zero chance that something is wrong with my graphics driver.

**Comment by Povstalec** [comment]
> java.lang.NoSuchMethodError

So like... the inherited method from Screen.java can't be found? I have no clue how that might even be happening. Could it be a Forge thing?

**Comment by Noobly-Walker** [comment]
I did some testing. I had pressing [F3] cause a crash, but that's Optifine's fault. Oddly enough, Optifine is the reason pressing [G] doesn't cause a crash. Without Optifine, [G] does still cause a crash.

**Comment by Noobly-Walker** [comment]
It works fine in 1.20.1. The mod does not properly support 1.20.2. Now I just feel silly.
Not a bug, I'm using this mod in the wrong version. As if I have a choice. Making a modpack for 1.20.X is difficult.

**Comment by Povstalec** [comment]
Ah, okay that makes sense. Hypothetically I might release the next update for more versions, depending on how much of a pain it will be to port things.
